version: "3.9"

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13.3-management-alpine
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    env_file:
      - ./.env
    ports:
      - 5672:5672
      - 15672:15672
    restart:
      always

volumes:
  rabbitmq_data:
    driver: local
